---
- name: Install Postfix MTA
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ postfix_packages }}"

- name: Install postgrey
  package:
    name: postgrey
    state: present
  when: check_policy.enabled

- name: Copy postfix configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/postfix/{{ item }}"
  with_items:
    - master.cf
    - main.cf
    - virtual_domains.cf
    - virtual_mailboxes.cf
    - virtual_aliases.cf
    - virtual_aliases_regex.cf
  notify:
    - Restart Postfix

- name: Copy postfix explicitly trusted sender domains
  template:
    src: "{{ item }}"
    dest: "/etc/postfix/{{ item }}"
  with_items:
    - sender_permits
  notify:
    - Restart Postfix
  register: sender_domains

- name: Ensure hash db for explicitly trusted sender domains
  command: postmap /etc/postfix/sender_permits
  when: sender_domains.changed

- name: Create group for managing mailboxes
  group:
    name: vmail
    gid: 5000

- name: Create user for managing mailboxes
  user:
    name: vmail
    uid: 5000
    group: vmail
    shell: '/bin/false'

- import_tasks: postfixadmin.yml
  tags: postfixadmin
