---
- name: Install postfixadmin
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postfixadmin
    - php-mbstring
    - php-fpm

- name: Create hashed password for superuser
  shell: "echo '{{ postfixadmin_superpass }}' | openssl passwd -1 -stdin"
  register: hashed_superpass

- name: Check if database exists
  shell:
    cmd:
      mysql -e 'select count(*) from postfix.admin;'
  become: yes
  become_user: root
  failed_when: False
  register: dbstatus

- name: Copy DB schema
  template:
    src: sql/01_postfixdb.sql
    dest: /tmp/01_postfixdb.sql
  when: dbstatus.rc != 0

- name: Import DB schema
  mysql_db:
    name: "{{ postfix_db_name }}"
    state: import
    target: /tmp/01_postfixdb.sql
    login_unix_socket: /run/mysqld/mysqld.sock
  when: dbstatus.rc != 0

- name: Use proper mysql connection type for postfixadmin
  lineinfile:
    path: /etc/postfixadmin/dbconfig.inc.php
    regexp: '.*dbtype=.*'
    line: "$dbtype='mysqli';"

- name: Use proper db password for postfixadmin
  lineinfile:
    path: /etc/postfixadmin/dbconfig.inc.php
    regexp: '.*dbpass=.*'
    line: "$dbpass='{{ postfixadmin_db_password }}';"

- name: Use proper db name for postfixadmin
  lineinfile:
    path: /etc/postfixadmin/dbconfig.inc.php
    regexp: '.*dbname=.*'
    line: "$dbname='{{ postfix_db_name }}';"

- name: Use proper setup password postfixadmin
  lineinfile:
    path: /etc/postfixadmin/config.inc.php
    regexp: '.*setup_password.*'
    line: "$CONF['setup_password'] = '';"

- name: Disable domain name checking
  lineinfile:
    path: /etc/postfixadmin/config.inc.php
    regexp: '.*emailcheck_resolve_domain.*'
    line: "$CONF['emailcheck_resolve_domain']='NO';"

- name: Disable prefix creation
  lineinfile:
    path: /etc/postfixadmin/config.inc.php
    regexp: '.*create_mailbox_subdirs_prefix.*'
    line: "$CONF['create_mailbox_subdirs_prefix']='';"

- name: Remove apache2 installation
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - apache2
    - lighttpd
